# Generated by Django 5.0.6 on 2024-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_42_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in_with_42',
            field=models.BooleanField(default=False),
        ),
    ]
