# Generated by Django 5.0.6 on 2024-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_user_logged_in_with_42'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_method',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_link',
            field=models.CharField(blank=True, default='https://cdn.intra.42.fr/users/8df16944f4ad575aa6c4ef62f5171bca/acarlott.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logged_in_with_42',
            field=models.BooleanField(default=True),
        ),
    ]
