# Generated by Django 5.0.6 on 2024-06-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authenticator_secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
