# Generated by Django 5.0.6 on 2024-06-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_verified_user_otp_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret_key',
        ),
    ]
