# Generated by Django 5.0.6 on 2024-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_verified_user_two_factor_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
