# Generated by Django 5.0.6 on 2024-07-09 08:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_profile_image_link_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=account.models.user_directory_path),
        ),
    ]
