services:
  # --> FRONTEND SERVICE <-- #
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./frontend/static:/var/www/static
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    networks:
      - transcendence-network
  # --> USER SERVICE <-- #
  user:
    container_name: user
    restart: always
    build:
      context: ./backend/user_service
      dockerfile: docker/Dockerfile
    image: user
    env_file: ./backend/.env
    command: >
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend/user_service:/app
    ports:
      - "8000:8000"
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - transcendence-network
  # --> AUTH SERVICE <-- #
  auth:
    container_name: auth
    restart: always
    build:
      context: ./backend/auth_service
      dockerfile: docker/Dockerfile
    image: auth
    env_file: ./backend/.env
    command: >
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend/auth_service:/app
    ports:
      - "8001:8000"
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - transcendence-network
  # --> TWOFACTOR SERVICE <-- #
  twofactor:
    container_name: twofactor
    restart: always
    build:
      context: ./backend/twofactor_service
      dockerfile: docker/Dockerfile
    image: twofactor
    env_file: ./backend/.env
    command: >
      sh -c "
          python3 manage.py makemigrations &&
          python3 manage.py migrate &&
          python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend/twofactor_service:/app
    ports:
      - "8002:8000"
    depends_on:
      twofactor_db:
        condition: service_healthy
    networks:
      - transcendence-network
 # --> FRIENDS SERVICE <-- #
  friends:
    container_name: friends
    restart: always
    build:
      context: ./backend/friends_service
      dockerfile: docker/Dockerfile
    image: friends
    env_file: ./backend/.env
    command: >
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 --verbosity 3 friends_service.asgi:application
      "
    volumes:
      - ./backend/friends_service:/app
    ports:
      - "8003:8000"
    depends_on:
      friends_db:
        condition: service_healthy
    networks:
      - transcendence-network
  # --> NOTIFICATIONS SERVICE <-- #
  notifications:
    container_name: notifications
    restart: always
    build:
      context: ./backend/notifications_service
      dockerfile: docker/Dockerfile
    image: notifications
    env_file: ./backend/.env
    command: >
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend/notifications_service:/app
    ports:
      - "8004:8000"
    depends_on:
      notifications_db:
        condition: service_healthy
    networks:
      - transcendence-network
  # --> DATABASE TWOFACTOR <-- #
  twofactor_db:
    container_name: twofactor_db
    image: postgres
    restart: always
    env_file: ./backend/.env
    environment:
      - POSTGRES_USER=${TWOFACTOR_DB_USER}
      - POSTGRES_DB=${TWOFACTOR_DB_NAME}
      - POSTGRES_PASSWORD=${TWOFACTOR_DB_PASSWORD}
    shm_size: 128mb
    volumes:
      - twofactor_pgdata:/var/lib/postgresql/data
    networks:
      - transcendence-network
    ports: 
     - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TWOFACTOR_DB_USER} -d ${TWOFACTOR_DB_NAME}"]
      interval: 8s
      timeout: 5s
      retries: 5
  # --> DATABASE AUTH <-- #
  auth_db:
    container_name: auth_db
    image: postgres
    restart: always
    env_file: ./backend/.env
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    shm_size: 128mb
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - transcendence-network
    ports: 
     - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 8s
      timeout: 5s
      retries: 5
  # --> DATABASE USER <-- #
  user_db:
    container_name: user_db
    image: postgres
    restart: always
    env_file: ./backend/.env
    environment:
      - POSTGRES_USER=${USER_DB_USER}
      - POSTGRES_DB=${USER_DB_NAME}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
    shm_size: 128mb
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - transcendence-network
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}"]
      interval: 8s
      timeout: 5s
      retries: 5
  # --> DATABASE FRIENDS <-- #
  friends_db:
    container_name: friends_db
    image: postgres
    restart: always
    env_file: ./backend/.env
    environment:
      - POSTGRES_USER=${FRIENDS_DB_USER}
      - POSTGRES_DB=${FRIENDS_DB_NAME}
      - POSTGRES_PASSWORD=${FRIENDS_DB_PASSWORD}
    shm_size: 128mb
    volumes:
      - friends_pgdata:/var/lib/postgresql/data
    networks:
      - transcendence-network
    ports:
     - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FRIENDS_DB_USER} -d ${FRIENDS_DB_NAME}"]
      interval: 8s
      timeout: 5s
      retries: 5
  # --> DATABASE NOTIFICATIONS <-- #
  notifications_db:
    container_name: notifications_db
    image: postgres
    restart: always
    env_file: ./backend/.env
    environment:
      - POSTGRES_USER=${NOTIFICATIONS_DB_USER}
      - POSTGRES_DB=${NOTIFICATIONS_DB_NAME}
      - POSTGRES_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}
    shm_size: 128mb
    volumes:
      - notifications_pgdata:/var/lib/postgresql/data
    networks:
      - transcendence-network
    ports:
     - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NOTIFICATIONS_DB_USER} -d ${NOTIFICATIONS_DB_NAME}"]
      interval: 8s
      timeout: 5s
      retries: 5

volumes:
  user_pgdata:
    name: user_data
  auth_pgdata:
    name: auth_data
  twofactor_pgdata:
    name: twofactor_data
  friends_pgdata:
    name: friends_data
  notifications_pgdata:
    name: notifications_data

networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge